version: "3.9"

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

